# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-27 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shrtnr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='full_url',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
