# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-27 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shrtnr', '0002_url_full_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shortened_url',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
