# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-31 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shrtnr', '0003_url_shortened_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='full_url',
            field=models.CharField(default=b'', max_length=255, unique=True),
        ),
    ]
